#ifndef ATOMSCANCODE_HPP
#define ATOMSCANCODE_HPP

#include "Pch.hpp"

typedef enum
{
    ATOM_SCANCODE_UP = 38,
    ATOM_SCANCODE_DOWN = 40,
    ATOM_SCANCODE_LEFT = 37,
    ATOM_SCANCODE_RIGHT = 39,
    ATOM_SCANCODE_D = 68,
    ATOM_SCANCODE_P = 80,
    ATOM_SCANCODE_T = 84,
    ATOM_SCANCODE_X = 88,
    ATOM_SCANCODE_Z = 90,
    ATOM_NUM_SCANCODES = 9,

} AtomScancode;

#endif