#ifndef ATOMSCANCODE_HPP
#define ATOMSCANCODE_HPP

#include "Pch.hpp"

typedef enum
{
    ATOM_SCANCODE_UP = 87,
    ATOM_SCANCODE_DOWN = 83,
    ATOM_SCANCODE_LEFT = 65,
    ATOM_SCANCODE_RIGHT = 68,
    ATOM_SCANCODE_E = 69,
    ATOM_SCANCODE_Q = 81,
    ATOM_SCANCODE_P = 80,
    ATOM_SCANCODE_T = 84,
    ATOM_SCANCODE_X = 88,
    ATOM_SCANCODE_Z = 90,
    ATOM_SCANCODE_G = 71,
    ATOM_SCANCODE_H = 72,
    ATOM_SCANCODE_NEXT_LEVEL = 49,
    ATOM_SCANCODE_PREV_LEVEL = 50,
    ATOM_NUM_SCANCODES = 13,

} AtomScancode;

#endif